RESET MASTER;

SET GLOBAL max_connections=5000;
SET GLOBAL gtid_strict_mode=ON;

CHANGE MASTER TO MASTER_HOST='10.10.10.145', MASTER_PORT=3310, MASTER_USER='maxscale_user', MASTER_PASSWORD='n9qSFvjZknc8pjrz', MASTER_USE_GTID=slave_pos;
START SLAVE;
